Add function process_fci() for rutokenS
AktivCo/OpenSC pull request #2
Opened 2018-01-15 12:19 UTC by Mardalemer

2018-01-24 13:33 UTC, dfortinskiy commented
merge, add commit message and lgtm

2018-01-26 11:30 UTC, lolyonok requested changes

2018-01-26 11:30 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +		/* Here means only leading byte. */
Only leading byte is significant

2018-01-26 11:30 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +		/* Here means only leading byte. */
надо определиться комменты с большой или маленькой буквы

2018-01-26 11:30 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +		file->shareable = tag[0] & 0x40 ? 1 : 0;
нужна ли проверка? или у нас всегда 0?

2018-01-26 11:30 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +		sc_file_set_prop_attr(file, tag, taglen);
скобки вроде тут не ставятся на однострочные if

2018-01-26 11:30 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +	tag = sc_asn1_find_tag(card->ctx, buf, buflen, 0x8A, &taglen);
у нас используется этот тэг?
бывают ли у нас неактивированные файлы

2018-01-31 07:07 UTC, lolyonok requested changes

2018-01-31 07:07 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +	if (tag != NULL && taglen == 2) {
открывающие скобки с новой строки

2018-01-31 07:07 UTC, lolyonok commented on src/libopensc/card-rutoken.c
> +	if (tag != NULL && taglen == 1)
стоит поставить скобки

2018-01-31 08:15 UTC, lolyonok approved these changes

2018-01-31 08:16 UTC, lolyonok commented
схлопнуть в один коммит и lgtm

2019-02-26 10:11 UTC, closed without merging